import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import tw from "tailwind-styled-components";
import Link from "next/link";
import CartIcon from "@/features/cart/CartIcon";
import CartContextProvider from "@/lib/context/CartContextProvider";
import DrawerContext from "@/lib/context/DrawerContext";
import PlusIcon from "@/features/product/PlusIcon";
import { NextResponse } from "next/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  ...p
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-white flex flex-col min-h-screen`}
      >
        <CartContextProvider>
          <DrawerContext>
            <header className="border-b-2 sticky top-0 bg-white z-30">
              <Container className="lg:py-4 py-3 flex justify-between items-center">
                <Link href={"/"} className="font-semibold text-lg md:text-xl">
                  E-commerce
                </Link>
                <div className="flex items-center gap-6">
                  <PlusIcon />
                  <CartIcon />
                </div>
              </Container>
            </header>
            <Container className="py-5 relative w-full flex-1">
              {children}
            </Container>
          </DrawerContext>
        </CartContextProvider>
      </body>
    </html>
  );
}

const Container = tw.main`mx-auto max-w-7xl md:px-14 px-4`;
